#  autogenerated file.
#  changes will be overwritten when running scripts\update_exampledata_init.py
import pathlib
root = pathlib.Path(__file__).parent

L8_NIR_SWIR_Red_qml = (root / 'L8_NIR_SWIR_Red.qml').as_posix()
LC08_L1TP_227065_20191129_20191216_01_T1_BQA_subset_tif = (root / 'LC08_L1TP_227065_20191129_20191216_01_T1.BQA.subset.tif').as_posix()
LC08_L1TP_227065_20191129_20191216_01_T1_TOA_subset_tif = (root / 'LC08_L1TP_227065_20191129_20191216_01_T1.TOA.subset.tif').as_posix()
